{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.tls.clusterIssuer }}"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.host }}"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: n8n-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: n8n-service
                port:
                  number: 80
{{- end }}
