apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.postgresPassword }}
  POSTGRES_NON_ROOT_USER: {{ .Values.postgres.auth.appUser }}
  POSTGRES_NON_ROOT_PASSWORD: {{ .Values.postgres.auth.appPassword }}
